<template>
  <div>

      <!-- DON'T NEED TO ADD ANYTHING IN THIS TEMPLATE
      We need this VUE component for NuxtJS to generate 404.html,
      which will be referred to by GitHub Static Hosting service to display 404 error. 
      The static page 404.html generated by nuxtJs will include HTML and JS implemented in layout/error.vue 
      
      So, this 404.vue along with 404.md is just for GitHub usage only. When we run this entire static
      website locally, all we need to display error 404 is layouts/error.vue
      -->
  </div>
</template>
